default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  password: 1234

development:
  <<: *default
  database: ruby_on_rails_lms_development

test:
  <<: *default
  database: ruby_on_rails_lms_test

production:
  <<: *default
  database: ruby_on_rails_lms_production
  username: ruby_on_rails_lms
  password: <%= ENV["RUBY_ON_RAILS_LMS_DATABASE_PASSWORD"] %>
